### ISSUE TITLE
Application not working

### ISSUE THREAD

**Issue by Kewal89** [aakashmanjrekar11/ChatGPT-Clone#1]
The appication is not working for me. It is showing the following message. Please fix.

My wifi is full, it is showing 3 bars but the application is still not working. why ? 

![image](https://user-images.githubusercontent.com/43823249/222968837-d2357e1a-2b3b-4cfd-be24-6e8b2887f3d3.png)

**Comment by aakashmanjrekar11** [comment]
Hello Kewal, thank you for opening the issue. 

I am aware of the issue, the application is throwing the error message (as described in your attached image) because the project has used up all the credits available in the OpenAI API free trial.
![image](https://user-images.githubusercontent.com/35526711/222996937-4846b686-7a9a-4d24-b5a2-3a49c24b561c.png)

Because the application cannot get a reply back from the API, it cannot function, so unfortunately I have stopped the live demo for this project.
